### ISSUE TITLE
custom header in origin arguments?

### ISSUE THREAD

**Issue by bmacauley** [terraform-aws-modules/terraform-aws-cloudfront#1]
We are  using Cloudfront as a reverse proxy for an Auth0 custom login domain. The configuration requires a custom header in the origin...
https://auth0.com/docs/custom-domains/configure-custom-domains-with-self-managed-certificates/configure-aws-cloudfront-for-use-as-reverse-proxy

is it possible to set up a customer header using this module?

**Comment by antonbabenko** [comment]
Hi @bmacauley !

You are right, this is not yet supported by the module but it definitely should be there and it is easy to fix.

Pull-request is welcome.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#custom_header

**Comment by antonbabenko** [comment]
Hi @bmacauley,

Please give a try to [v1.0.0](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/releases/v1.0.0) of this module which has been just released.
