### ISSUE TITLE
the ability to create access controls with the module

### ISSUE THREAD

**Issue by a-khaledf** [terraform-aws-modules/terraform-aws-cloudfront#102]
## Is your request related to a problem?
By using `create_origin_access_identity` you could create access identities to use with your origin, but there is no way to create access control using the module.
Since Access identities have become legacy, I think we need a way to create access controls as well using the module

## Describe the solution you'd like.
something like that would make sense
```
create_origin_access_control = true
origin_access_controls = {
    s3_bucket_one = {
      name                              = "example"
      description                       = "Example Policy"
      origin_access_control_origin_type = "s3"
      signing_behavior                  = "always"
      signing_protocol                  = "sigv4"
    }
 }
```

**Comment by skype007** [comment]
Seems the pull request #97 should address this issue.
