### ISSUE TITLE
Add support for decoupling FMS-managed web ACLs

### ISSUE THREAD

**Issue by theipster** [terraform-aws-modules/terraform-aws-cloudfront#111]
## Is your request related to a new offering from AWS?

Not new, the [AWS Firewall Manager (FMS)](https://docs.aws.amazon.com/waf/latest/developerguide/fms-chapter.html) service has been around for a number of years. Regardless, this feature request doesn't necessarily relate to any of the service's APIs anyway; in contrast, it's about how to decouple away from it.

## Is your request related to a problem? Please describe.

Amongst other things, AWS FMS supports the ability to configure a [web ACL](https://docs.aws.amazon.com/waf/latest/developerguide/web-acl.html) at an organization level to be automatically applied to CloudFront distributions within that organization.

In other words, a target state may involve a web ACL that is provisioned in account A (i.e. the _Firewall Manager administrator account_) being automatically applied to a CloudFront distribution provisioned in account B (another member account in the organization).

These two resources obviously have different lifecycles.

The problem is thus: if the above CloudFront distribution were to be deployed/managed via this `terraform-aws-cloudfront` module, the module's [`aws_cloudfront_distribution.web_acl_id` argument](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/main.tf#L39) will drift whenever the FMS-managed web ACLs get updated.

## Describe the solution you'd like.

The ability to **un**manage the `aws_cloudfront_distribution.web_acl_id` argument as necessary.

For module users who know that their CloudFront distribution will be impacted by FMS, the following Terraform configuration achieves the intended behaviour (confirmed):

```tf
resource "aws_cloudfront_distribution" "this" {
  ...

  lifecycle {
    ignore_changes = [
      web_acl_id,  # Ignore FMS-managed web ACLs
    ]
  }
}
```

However, the challenge is to _also_ continue supporting module users who have CloudFront distributions that are not impacted by FMS and want to manage web ACLs at the distribution level:

```tf
module "distribution" {
  source = "terraform-aws-modules/cloudfront/aws"
  
  ...
  
  web_acl_id = ...
}
```

Indeed, both use cases could even occur simultaneously within the same organization, because an FMS policy might be scoped to only apply to some, not all, CloudFront distributions within the organization. 

## Describe alternatives you've considered.

An alternative direction might be to dynamically lookup the FMS-managed web ACL's ID (which potentially falls outside the remit of the `terraform-aws-cloudfront` module) and then have the value bound to the module's `web_acl_id` input variable. Something like:

```tf
data "aws_wafv2_web_acl" "fms_managed_web_acl" {
  ...
}

module "distribution" {
  source = "terraform-aws-modules/cloudfront/aws"

  ...

  web_acl_id = data.aws_wafv2_web_acl.fms_managed_web_acl.id
}
```

However, there are a few challenges/downsides to this approach:

1. FMS-generated web ACLs have names that are difficult to determine dynamically. The naming logic is documented [here](https://docs.aws.amazon.com/waf/latest/developerguide/get-started-fms-create-security-policy.html) and requires knowing the exact creation time of the web ACL in the FMS administrator account:

   > 7\. For **Policy name**, enter a descriptive name. Firewall Manager includes the policy name in the names of the web ACLs that it manages. The web ACL names have `FMManagedWebACLV2-` followed by the policy name that you enter here, `-`, and the web ACL creation timestamp, in UTC milliseconds. For example, `FMManagedWebACLV2-MyWAFPolicyName-1621880374078`.

   This makes it impractical to lookup a web ACL by name.

2. Currently, the only way to lookup a web ACL is by name - via the [`data.aws_wafv2_web_acl`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/wafv2_web_acl) data source's `name` argument.

3. Generally, this approach introduces a lot more complexity compared to simply ignoring the `aws_cloudfront_distribution.web_acl_id`, especially given that we don't actually care what the ID is anyway, as we know it is managed by an external process.

## Additional context

- https://github.com/hashicorp/terraform/issues/27360

**Comment by theipster** [comment]
Bump.

**Comment by antonbabenko** [comment]
We can't do much about this until it becomes possible to use variables inside `ignore_changes` (https://github.com/hashicorp/terraform/issues/27360).

PS: I have another temporary solution in mind, so I will use your request (this issue) as a test case when I design it.
