### ISSUE TITLE
Documentation request for update https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/21

### ISSUE THREAD

**Issue by akumar-99** [terraform-aws-modules/terraform-aws-cloudfront#113]
## Describe the solution you'd like.
Please add a documentation for this patch https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/21. I had to find this issue to fix my error.

**Comment by antonbabenko** [comment]
Please open a PR with the suggested updates to the documentation.
