### ISSUE TITLE
Error: expected default_cache_behavior.0.function_association.0.event_type to be one of [viewer-request viewer-response origin-request origin-response], got 0

### ISSUE THREAD

**Issue by maciunio2** [terraform-aws-modules/terraform-aws-cloudfront#114]
https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/a1bc7ac16d5db2a5359659d1e4b0373a796950f1/main.tf#L180C1-L180C1
I think there is an error in this line. With current code version I get this error:
`Error: expected default_cache_behavior.0.function_association.0.event_type to be one of [viewer-request viewer-response origin-request origin-response], got 0`

**Comment by antonbabenko** [comment]
Hi @maciunio2 !

Please take a look into example - https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/a1bc7ac16d5db2a5359659d1e4b0373a796950f1/examples/complete/main.tf#L116-L128

The key in the map should be one of the required values.
