### ISSUE TITLE
custom_error_response when empty list

### ISSUE THREAD

**Issue by quentin9696** [terraform-aws-modules/terraform-aws-cloudfront#121]
## Description

Terraform produce an error when dealing with empty list on `var.custom_error_response` because of the way this module evaluate the variable. Because we use cloudfront in a module with validations, we can't have unmatched variables type

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
```
3.2.1
```
- Terraform version:
```
Terraform v1.6.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.24.0
```
- Provider version(s):
```
Terraform v1.6.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.24.0
```

## Reproduction Code [Required]

``` hcl
provider "aws" {}

variable "custom_error_response" {
  description = "Create one or multiples custom error response"
  type        = list(object({
    error_code            = number,
    response_code         = optional(number),
    response_page_path    = optional(string),
    error_caching_min_ttl = number
  }))
  default = []
}

module "cdn" {
  source = "terraform-aws-modules/cloudfront/aws"
  version = "3.2.1"

  enabled               = true
  default_root_object   = "/index.html"
  wait_for_deployment   = false
  custom_error_response = var.custom_error_response

  origin = {
    test = {
      domain_name = "foo.com"
      origin_id   = "test"
      custom_origin_config = {
        http_port              = 80
        https_port             = 443
        origin_protocol_policy = "match-viewer"
        origin_ssl_protocols   = ["TLSv1", "TLSv1.1", "TLSv1.2"]
      }
    }
  }
  default_cache_behavior = {
    target_origin_id       = "test"
    viewer_protocol_policy = "allow-all"
  }
}
```

Simply run terraform apply. 

## Expected behavior

No errors

## Actual behavior

```
│ Error: Invalid index
│ 
│   on .terraform/modules/cdn/main.tf line 261, in resource "aws_cloudfront_distribution" "this":
│  261:     for_each = length(flatten([var.custom_error_response])[0]) > 0 ? flatten([var.custom_error_response]) : []
│     ├────────────────
│     │ var.custom_error_response is empty list of object
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
```

## Additional context

I tried by removing changing `for_each = length(flatten([var.custom_error_response])[0]) > 0 ? flatten([var.custom_error_response]) : []` to `for_each = length(flatten([var.custom_error_response])) > 0 ? flatten([var.custom_error_response]) : []`, and everything is working well. 

I can make PR to fix

**Comment by cwong-archy** [comment]
seeing same issue. thanks for the PR ...

**Comment by yfougeray-pubfac** [comment]
Here is a way to make it works until it's fixed.
In case you don't want a custom_error_response, you can set [{}] as default value.

**Comment by cwong-archy** [comment]
> Here is a way to make it works until it's fixed. In case you don't want a custom_error_response, you can set `[{}]` as default value.

thanks.

i did a plan and it seems fine. but we have it pinned for now until the fix.
