### ISSUE TITLE
Unable to Delete Lambda@Edge Functions and Replicas

### ISSUE THREAD

**Issue by Ravi-Gupta77** [terraform-aws-modules/terraform-aws-cloudfront#126]
When the infrastructure is provisioned using this module then while destroying the infrastructure I'm unable to delete lambda edge function

**Comment by Ravi-Gupta77** [comment]
```Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; ╷
        	            	│ Error: deleting Lambda Function (lambda-g9hlg): operation error Lambda: DeleteFunction, https response error StatusCode: 400, RequestID: c50f9a93-eace-40b8-88b9-e8f3c543c36c, InvalidParameterValueException: Lambda was unable to delete arn:aws:lambda:us-east-1:***:function:lambda-g9hlg:1 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge Functions and Replicas.```

**Comment by Ravi-Gupta77** [comment]
Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; ╷
        	            	│ Error: deleting Lambda Function (lambda-g9hlg): operation error Lambda: DeleteFunction, https response error StatusCode: 400, RequestID: c50f9a93-eace-40b8-88b9-e8f3c543c36c, InvalidParameterValueException: Lambda was unable to delete arn:aws:lambda:us-east-1:***:function:lambda-g9hlg:1 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge Functions and Replicas.

**Comment by antonbabenko** [comment]
All the details are specified in the official AWS documentation - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-delete-replicas.html

From the module's perspective, we can't do anything else. You should just try running `terraform destroy` after some time.
