### ISSUE TITLE
ordered_cache_behavior issue with dissimilar behaviors

### ISSUE THREAD

**Issue by niallfleming** [terraform-aws-modules/terraform-aws-cloudfront#13]
When I try to plan/apply the following behaviors list, terraform (0.12.30) complains that all items in the list must be of the same type.

Error: The given value is not suitable for child module variable "ordered_cache_behavior" defined at .terraform/modules/totara_cdn/variables.tf:130,1-34: all list elements must have the same type.

```
ordered_cache_behavior = [
    {
      path_pattern           = "/cdn/*"
      target_origin_id       = "s3"
      viewer_protocol_policy = "allow-all"

      allowed_methods = ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
      headers = ["Access-Control-Request-Headers", "Access-Control-Request-Method", "Origin"]
      trusted_signers = ["self"]
    },
    {
      path_pattern = "lib/requirejs.php*"
      target_origin_id = "alb"
      viewer_protocol_policy = "allow-all"

      allowed_methods = ["GET", "HEAD"]
      headers = ["Host"]
      query_string = true
    },
]
```

I can get it to accept the second item, only if all keys are present:
```
    query_string = false
    },
    {
      path_pattern = "lib/requirejs.php*"
      target_origin_id = "alb"
      viewer_protocol_policy = "allow-all"

      allowed_methods = ["GET", "HEAD"]
      headers = ["Host"]
      trusted_signers = []
      query_string = true
    },
```

Is this expected? Or is there a better workaround?

**Comment by antonbabenko** [comment]
This looks like a bug that should be fixed in the module if you or anyone else have time.

**Comment by niallfleming** [comment]
Ah great! I wasn't going insane, I'm afraid I don't know enough TF to fix it, otherwise I would have ;)

**Comment by mike-carey** [comment]
Terraform expects all elements within a list to be of the same type; that is, both objects must have the same keys present.

[Reference](https://www.terraform.io/docs/language/expressions/type-constraints.html#list-)

**Comment by niallfleming** [comment]
So it could be ok for TF 0.14, with optional args. enabled.

"
From Terraform v0.14 there is experimental support for marking particular attributes as optional in an object type constraint.

To mark an attribute as optional, use the additional optional(...) modifier around its type declaration
"

So sounds like no way round it for now, not without losing ordering.

**Comment by sc250024** [comment]
Just ran into this as well. It seems that the `optional` experiment mentioned above might be a solution. Is this something that the module is willing to support (i.e. an `experiments` section) ?

**Comment by antonbabenko** [comment]
We can only use Terraform 0.13 features in these modules because of the wide range of users/versions. In 90% of cases, there is no need to use even those, and we can use features of 0.12.

This issue is just a bug. PR is welcome.

**Comment by antonbabenko** [comment]
[v1.9.0](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/releases/v1.9.0) has been just released.
