### ISSUE TITLE
Support for Staging Distributon

### ISSUE THREAD

**Issue by ogugu9** [terraform-aws-modules/terraform-aws-cloudfront#131]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

CHANGELOG: https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5120-august-10-2023
> New Resource: aws_cloudfront_continuous_deployment_policy (https://github.com/hashicorp/terraform-provider-aws/issues/32936)

## Is your request related to a problem? Please describe.

In order to use staging distribution, we must set `staging = true` to the staging distribution and specify `continuous_deployment_policy_id` for the primary distribution.
However, this module doesn't support these variables.

## Describe the solution you'd like.

* Add `staging` variable.
* Add `continuous_deployment_policy_id` variable.

I created PR: https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/130

## Describe alternatives you've considered.

* Give up on using this module and use AWS Provider directly.

**Comment by ogugu9** [comment]
@antonbabenko @bryantbiggs 
I'm sorry, could you check this issue and corresponding PR https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/130 ...?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.3.0 :tada:
