### ISSUE TITLE
The argument "origin" cannot set to the multiples

### ISSUE THREAD

**Issue by phisinees** [terraform-aws-modules/terraform-aws-cloudfront#14]
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Attribute redefined

  on xxx.tf line 133, in module "xxx":
 133:   origin = {

The argument "origin" was already set at xxx linexx. Each
argument may be set only once.

----------------------------------------

ex.

 `
origin = {
    domain_name = "xxx.s3.amazonaws.com"
    origin_id   = "S3-xxx/production"
    origin_path = "/production"
    s3_origin_config = {
      origin_access_identity = aws_cloudfront_origin_access_identity.xxx.cloudfront_access_identity_path
    }
  }

  origin = {
    domain_name = "pmlo-test.s3.amazonaws.com"
    origin_id   = "S3-xxx/staging"
    origin_path = "/staging"
    s3_origin_config = {
      origin_access_identity = aws_cloudfront_origin_access_identity.xxx.cloudfront_access_identity_path
    }
  }
`

**Comment by antonbabenko** [comment]
You need to specify `origin` as a map of map. Please look at the examples:

https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/f13514ff6c66e37458b0d00ba3bd815d8c30855d/examples/complete/main.tf#L41-L70
