### ISSUE TITLE
origin_access_control_id not implemented

### ISSUE THREAD

**Issue by skkiran-pro** [terraform-aws-modules/terraform-aws-cloudfront#144]
## Description

We can only use the legacy origin_access_identity like below:
  ```
origin = {
    default = {
      domain_name      = module.web_app.s3_bucket_bucket_regional_domain_name
      s3_origin_config = {
        origin_access_identity = "web_app" 
      }
    }
  }
```

origin_access_control does not work:
```
  origin = {
    default = {
      domain_name              = module.web_app.s3_bucket_bucket_regional_domain_name
      origin_id                = module.web_app.s3_bucket_id
      origin_access_control_id = aws_cloudfront_origin_access_control.test.id
    }
  } 
```

**Comment by andrei-gabriel-p** [comment]
I can also confirm that its not working as the code states. had to use the next config

origin = {

    s3_one = {
      domain_name = "testbucket.s3.eu-west-1.amazonaws.com"
      origin_id   = "s3-my-private-bucket"
      origin_access_control = "oac"
    }
  }

**Comment by Duceswild99** [comment]
+1 This is not working as intended. 

As a workaround (I am not proud of this and it should be thrown in a corner somewhere), you can have the module refer to itself, and manually pass in the origin_access_control_id.

```
      origin_access_control_id = module.this.cloudfront_origin_access_controls_ids[0]
```

**Comment by stadskle** [comment]
Any updates on this? Just started using this and wanted not to implement legacy config in a new project, but I am experiencing the same issue.

**Comment by antonbabenko** [comment]
There are two ways to achieve the same result:
1. `origin_access_control_id` - expects ID of the resource created externally from the module (e.g. `E345SXM82MIOSU`)
2. `origin_access_control` - key in the `origin_access_control` argument created by the module.

See this example for more details: https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/examples/complete/main.tf#L96-L101

The workaround by @Duceswild99 can be like:
```
     origin_access_control = "key_from_origin_access_control" # created by this module
```
