### ISSUE TITLE
Add support for CloudFront VPC origins

### ISSUE THREAD

**Issue by MattiaEffendi** [terraform-aws-modules/terraform-aws-cloudfront#152]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: Introduced in [version v5.82.0](https://github.com/hashicorp/terraform-provider-aws/blob/v5.82.0/CHANGELOG.md)

## Describe the solution you'd like.
I would expect to be able to create a VPC origin and add it as an origin for my CloudFront distribution.

## Describe alternatives you've considered.
At the moment there are no alternatives

## Additional context
- [VPC origin release blog post (AWS side)](https://aws.amazon.com/blogs/aws/introducing-amazon-cloudfront-vpc-origins-enhanced-security-and-streamlined-operations-for-your-applications/)
- [Terraform AWS provider `aws_cloudfront_vpc_origin` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_vpc_origin)

**Comment by antonbabenko** [comment]
Please open a PR for this feature

**Comment by destornillador** [comment]
I will send a PR between tonight (CET) and tomorrow.
