### ISSUE TITLE
Support for aws_cloudfront_realtime_log_config

### ISSUE THREAD

**Issue by seanturner026** [terraform-aws-modules/terraform-aws-cloudfront#16]
Terraform was lacking support for this resource for months, and was released recently.

Terraform Resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_realtime_log_config

Cloudfront needs an role ARN to write logs to the kinesis stream.

One way of doing it would be to create a new variable `enable_cloudfront_realtime_log_config`.

This variable being present unlocks the creation of a `role`, `role_policy`, and `aws_cloudfront_realtime_log_config`

**Comment by rom1gal** [comment]
+1 for that

**Comment by antonbabenko** [comment]
PR is welcome

**Comment by rom1gal** [comment]
@antonbabenko  : Done https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/31 (a simple PR, hope it will help)

**Comment by antonbabenko** [comment]
#31 has added read-only integration for the `realtime_log_config_arn` to use an existing resource.

The bigger pull request that adds the required resources ([like here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_realtime_log_config)) is still missing if anyone has some time.
