### ISSUE TITLE
The parameter ForwardedValues cannot be used when a cache policy is associated to the cache behavior

### ISSUE THREAD

**Issue by nodomain** [terraform-aws-modules/terraform-aws-cloudfront#20]
Thanks for adding the cache and origin request policy support.

Unfortunately this does not work:

```
...
  default_cache_behavior = {
    target_origin_id       = "webapp"
    viewer_protocol_policy = "redirect-to-https"

    allowed_methods = ["GET", "HEAD", "OPTIONS"]
    cached_methods  = ["GET", "HEAD"]
    compress        = true

    cache_policy_id          = aws_cloudfront_cache_policy.default.id
    origin_request_policy_id = aws_cloudfront_origin_request_policy.default.id
  }
...
```

Results in:

```
Error: error updating CloudFront Distribution (xxx): InvalidArgument: The parameter ForwardedValues cannot be used when a cache policy is associated to the cache behavior.
        status code: 400, request id: 764d6b38-ee58-4e88-bd1a-49d112cc6f7f
```

I suspect that the block here needs to be added conditionally: https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/main.tf#L115-L124

Thanks for fixing :)

**Comment by nodomain** [comment]
This is obviously a known bug in the Terraform provider, as I learned by reading through https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/17

https://github.com/hashicorp/terraform-provider-aws/issues/17626

**Comment by christiansaiki** [comment]
@nodomain  This will be probably be fixed with #21

**Comment by antonbabenko** [comment]
Fixed in #21 

[v1.8.0](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/releases/v1.8.0) has been just released.

**Comment by rakitadragan** [comment]
Thank you for great work!
It would save me couple of hours if this variable was documented in README.md :-)

**Comment by antonbabenko** [comment]
@rakitadragan We always try to create examples to show the most common solutions 100% working and executable right away.

Check the `examples` folder in any [terraform-aws-modules repo](https://github.com/terraform-aws-modules) if you ever stuck.

**Comment by violenti** [comment]
Hi, in the example of  terraform-aws-cloudfront not specify  the use of forwarded, only be to use use_forwarded_values as  false
