### ISSUE TITLE
Terraform module not picking up forwarded_values

### ISSUE THREAD

**Issue by zsarion** [terraform-aws-modules/terraform-aws-cloudfront#22]
Hi guys,
I'm having an issue with the terraform-aws-cloudfront not picking up the forwarded_values code block. 
This is my code for the ordered_cache_behavior:

  ordered_cache_behavior = [
    {
      path_pattern           = "/components/*"
      target_origin_id       = "angular"
      viewer_protocol_policy = "redirect-to-https"

      allowed_methods = ["GET", "HEAD", "OPTIONS"]
      cached_methods  = ["GET", "HEAD", "OPTIONS"]
      compress        = true
      query_string    = true
      forwarded_values = {
        query_string = false,
        headers      = ["Origin", "Access-Control-Request-Headers", "Access-Control-Request-Method"]
      }
    }
  ]

When I do a TF plan, Terraform does not seem to pickup the forwarded_values:

forwarded_values {
                headers                 = []
                query_string            = true
                query_string_cache_keys = []
                cookies {
                    forward           = "none"
                    whitelisted_names = []
                }
            }

The code itself does not error out. I can still proceed doing an apply but obviously, my changes will not be implemented.            
I saw an issue earlier that the forwarded_values will not work when there is a cache policy set, but I don't think I configured mine to use one.

**Comment by antonbabenko** [comment]
Hi @zsarion !

There is already #20 and #21 which will be merged soon.

**Comment by christiansaiki** [comment]
@antonbabenko this is a different issue than reported in #20
But actually, it's not an issue. @zsarion you'll have to read the code so that you understand how the forwarded_values work.
Check https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/main.tf#L162

In order to set the forwarded_values you would need to do:
```tf
ordered_cache_behavior = [{
path_pattern = "/components/*"
target_origin_id = "angular"
viewer_protocol_policy = "redirect-to-https"

  allowed_methods = ["GET", "HEAD", "OPTIONS"]
  cached_methods  = ["GET", "HEAD", "OPTIONS"]
  compress        = true
  query_string = false
  headers      = ["Origin", "Access-Control-Request-Headers", "Access-Control-Request-Method"]
}]
```
