### ISSUE TITLE
Change custom_error_response variable type

### ISSUE THREAD

**Issue by aferreeira** [terraform-aws-modules/terraform-aws-cloudfront#28]
https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/ddf49a7b736cf25057f716e13f7c11a193624ac9/variables.tf#L118-L122

I think that would be better having the right type for the variable `custom_error_response`, since I didn't find any example using this variable.

**Comment by imaginarynik** [comment]
Take a look at my example here to solve your problem:
https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/29#discussion_r628146177

**Comment by cageyv** [comment]
This example should help

```hcl
custom_error_response = {
    error404 = {
      error_code            = 404
      error_caching_min_ttl = 300
      response_code         = 200
      response_page_path    = "/index.html"
    }
  }
```

**Comment by antonbabenko** [comment]
Yes, also there can be multiple `custom_error_response` values in a `map` as @cageyv showed.

Closing the issue.
