### ISSUE TITLE
Add support for trusted_key_groups on cache behaviours

### ISSUE THREAD

**Issue by rlvrs** [terraform-aws-modules/terraform-aws-cloudfront#30]
## Is your request related to a new offering from AWS?
The AWS provider for terraform added support for `trusted_key_groups` recently. 

## Is your request related to a problem? Please describe.
I can now terraform cloudfront public keys and key groups.
However, it is sad that it is not possible to terraform the `trusted_key_groups` to an ordered cache behaviour.

**Comment by antonbabenko** [comment]
[v2.1.0](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/releases/v2.1.0) has been just released.
