### ISSUE TITLE
Modification or adding new custom origin replaces every other custom origin

### ISSUE THREAD

**Issue by imaginarynik** [terraform-aws-modules/terraform-aws-cloudfront#37]
## Modification to domain name or adding new custom origin to my config shows a plan that adds replaces every other custom origin which should be untouched

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## Versions

 - Terraform:
v0.13.7
 - Provider(s):
3.28.0
 - Module:
1.9.0 (faced same problem with cdn 2.2.0 version of module)

## Reproduction
Try changing the domain name of custom origin, or adding a new custom origin like API Gateway to the config, and the plan that results out of this small change is that 
 NO
 YES

1. terraform init
2. Correction of the typo or adding of a new block of code for a new custom origin 
3. terraform plan
4. Suddenly the plan now wants to remove and re-add other custom origins!!! 

Why should it try to touch other origins? 

      - origin {
          - domain_name = "slbwa.execute-api.eu-central-1.amazonaws.com" -> null
          - origin_id   = "api_pr" -> null

          - custom_origin_config {
              - http_port                = 80 -> null
              - https_port               = 443 -> null
              - origin_keepalive_timeout = 5 -> null
              - origin_protocol_policy   = "https-only" -> null
              - origin_read_timeout      = 30 -> null
              - origin_ssl_protocols     = [
                  - "TLSv1.2",
                ] -> null
            }
        }
      + origin {
          + domain_name = "slbwa.execute-api.eu-central-1.amazonaws.com"
          + origin_id   = "api_pr"

          + custom_origin_config {
              + http_port                = 80
              + https_port               = 443
              + origin_keepalive_timeout = 5
              + origin_protocol_policy   = "https-only"
              + origin_read_timeout      = 30
              + origin_ssl_protocols     = [
                  + "TLSv1.2",
                ]
            }
        }
      - origin {
          - domain_name = "t0pmutn.execute-api.eu-central-1.amazonaws.com" -> null
          - origin_id   = "api_br" -> null

          - custom_origin_config {
              - http_port                = 80 -> null
              - https_port               = 443 -> null
              - origin_keepalive_timeout = 5 -> null
              - origin_protocol_policy   = "https-only" -> null
              - origin_read_timeout      = 30 -> null
              - origin_ssl_protocols     = [
                  - "TLSv1.2",
                ] -> null
            }
        }
      + origin {
          + domain_name = "t0pmu.execute-api.eu-central-1.amazonaws.com"
          + origin_id   = "api_br"

          + custom_origin_config {
              + http_port                = 80
              + https_port               = 443
              + origin_keepalive_timeout = 5
              + origin_protocol_policy   = "https-only"
              + origin_read_timeout      = 30
              + origin_ssl_protocols     = [
                  + "TLSv1.2",
                ]
            }
        }

## Expected behavior
Typo Correction in API Gateway slbwa.execute-api.eu-central-1.amazonaws.com should only result in change in that origin and leave other origins untouched. Also, adding of a new origin should keep the other origins untouched

## Actual behavior

It tried to add and remove all other origins - which could result in downtime

### Terminal Output Screenshot(s)

      - origin {
          - domain_name = "slbwa.execute-api.eu-central-1.amazonaws.com" -> null
          - origin_id   = "api_pr" -> null

          - custom_origin_config {
              - http_port                = 80 -> null
              - https_port               = 443 -> null
              - origin_keepalive_timeout = 5 -> null
              - origin_protocol_policy   = "https-only" -> null
              - origin_read_timeout      = 30 -> null
              - origin_ssl_protocols     = [
                  - "TLSv1.2",
                ] -> null
            }
        }
      + origin {
          + domain_name = "slbwa.execute-api.eu-central-1.amazonaws.com"
          + origin_id   = "api_pr"

          + custom_origin_config {
              + http_port                = 80
              + https_port               = 443
              + origin_keepalive_timeout = 5
              + origin_protocol_policy   = "https-only"
              + origin_read_timeout      = 30
              + origin_ssl_protocols     = [
                  + "TLSv1.2",
                ]
            }
        }
      - origin {
          - domain_name = "t0pmutn.execute-api.eu-central-1.amazonaws.com" -> null
          - origin_id   = "api_br" -> null

          - custom_origin_config {
              - http_port                = 80 -> null
              - https_port               = 443 -> null
              - origin_keepalive_timeout = 5 -> null
              - origin_protocol_policy   = "https-only" -> null
              - origin_read_timeout      = 30 -> null
              - origin_ssl_protocols     = [
                  - "TLSv1.2",
                ] -> null
            }
        }
      + origin {
          + domain_name = "t0pmu.execute-api.eu-central-1.amazonaws.com"
          + origin_id   = "api_br"

          + custom_origin_config {
              + http_port                = 80
              + https_port               = 443
              + origin_keepalive_timeout = 5
              + origin_protocol_policy   = "https-only"
              + origin_read_timeout      = 30
              + origin_ssl_protocols     = [
                  + "TLSv1.2",
                ]
            }
        }

**Comment by imaginarynik** [comment]
@antonbabenko Thank you so much for your response. I looked up open issues on the aws-provider and found the solution:
https://github.com/hashicorp/terraform-provider-aws/issues/12065#issuecomment-587518720

The problem with the AWS module could be solved by simply replacing "origin_path" to assume an empty string as **""** instead of _null_
 at https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/8d30085525039ec191bd647eff94ab1894fc63e9/main.tf#L42

**Comment by antonbabenko** [comment]
Interesting, good if it works for you. Please make a small PR for this.

**Comment by imaginarynik** [comment]
Great! I just opened the PR but it's failing for semantic title, I guess...other checks were fine..I'm a first-time committer too... :D

**Comment by imaginarynik** [comment]
Hey, that was quick! Thank you so much! :D
