### ISSUE TITLE
parameter ForwardedValues cannot be used when a cache policy is associated to the cache behavior

### ISSUE THREAD

**Issue by hemzet** [terraform-aws-modules/terraform-aws-cloudfront#40]
## Description

When associating a cache policy to the distribution Terraform stops apllying with an error that cache_policy_id must not be used at the same time as the forwarded_values section.

`Error: error creating CloudFront Distribution: InvalidArgument: The parameter ForwardedValues cannot be used when a cache policy is associated to the cache behavior.`

So, however I set or uncomment forwarded_values, the module at least creates an empty list (see line 116 in main.tf).

## Versions
Terraform v0.14.5
- provider registry.terraform.io/hashicorp/aws v3.42.0
- Module: aws_module_cloudfront v2.4.0

## Reproduction

Associate a cache_policy_id in the default cache section (or the ordered cache section) and run terraform apply. 

### Code Snippet to Reproduce
`default_cache_behavior = {
    target_origin_id       = "s3_origin"
    viewer_protocol_policy = "redirect-to-https"

    allowed_methods = ["GET", "HEAD", "OPTIONS"]
    cached_methods  = ["GET", "HEAD"]
    query_string    = true

    min_ttl                = 0
    default_ttl            = 86400
    max_ttl                = 31536000
    compress               = true

    cache_policy_id        = aws_cloudfront_cache_policy.S3RedirectCachePolicy.id

    lambda_function_association = {
      origin-request = {
        lambda_arn = module.lambda_edge.lambda_function_qualified_arn
      }
    }

    # parameter ForwardedValues cannot be used when a cache policy is associated to the cache behavior
    /*forwarded_values = {} 
    }*/
}`

## Expected behavior
Cache policy is applied.

## Actual behavior
Error message that forwarded values and cache policy id parameters must not be used together.

### Terminal Output Screenshot(s)
`Error: error creating CloudFront Distribution: InvalidArgument: The parameter ForwardedValues cannot be used when a cache policy is associated to the cache behavior.`

## Additional context
n/a

**Comment by christiansaiki** [comment]
@hemzet please check https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/21#issuecomment-785454307 for an example of how to deal with cache policy
