### ISSUE TITLE
function_association event_type returns "0" 

### ISSUE THREAD

**Issue by samparnell** [terraform-aws-modules/terraform-aws-cloudfront#44]
## Description

Setting a Cloudfront Function using this module fails to set the event_type parameter correctly. Running terraform plan/apply results in the event_type being set to "0".

Example config:
`
      function_association = [{
        event_type   = "viewer-request"
        function_arn = aws_cloudfront_function.SomeFunction.arn
      }]
`

Result in terraform plan:
`
 + function_association {
     + event_type   = "0"
     + function_arn = "arn:aws:cloudfront::123123123123:function/SomeFunction"
}
`

Error on Apply:
`
Error: error creating CloudFront Distribution: MalformedXML: 1 validation errors detected: Value '0' at 'distributionConfig.cacheBehaviors.items.1.member.functionAssociations.items.1.member.eventType' failed to satisfy constraint: Member must satisfy value set: [viewer-request, viewer-response]
`

## Versions

 - Terraform: v1.0.2

 - Provider(s): registry.terraform.io/hashicorp/aws v3.49.0

 - Module:

**Comment by jcuretti** [comment]
Any clue how to solve this issue yet?
