### ISSUE TITLE
variable issue aliases

### ISSUE THREAD

**Issue by ValeriKehayovUBB** [terraform-aws-modules/terraform-aws-cloudfront#50]
## Description

Dear Team,

I am trying to add additional alias 

![image](https://user-images.githubusercontent.com/83134296/129469665-daf5aa0e-f362-4acc-9d2d-05d934223d37.png)
I am using tfvar file to add the needed aliases 

![image](https://user-images.githubusercontent.com/83134296/129470442-dbb195a9-e16d-4ac7-bbba-43a4f6208bf6.png)

But In Terraform I am receiving following error: 

 
![image](https://user-images.githubusercontent.com/83134296/129470465-60d86e3a-d335-4067-b33f-743ff1c94fe2.png)

Any ideas why when I use simple: 

alias = "www.example.com"

is working 
and when I use
alias =["www.example.com", "example.com] 
is not working?

**Comment by ValeriKehayovUBB** [comment]
I saw my error, you can close this issue. 
The problem was that actually I am applying 2 times array so terrafrom reads it like this 

`cf_alias  = [["exmaple.com", "www.example.com"]]`
It should be like that in the module:
`aliases = var.cf_aliases`
`without [var.cf_aliases]` and it's working as expected

**Comment by antonbabenko** [comment]
Good that you found the solution.

Hint: If you see that variable name is plural (like `aliases`) then it is likely to accept a list.

Also, always check examples.
