### ISSUE TITLE
Cannot recreate/update Cloudfront Origin Access

### ISSUE THREAD

**Issue by GMartinez-Sisti** [terraform-aws-modules/terraform-aws-cloudfront#61]
## Description

Performing an update that requires a new Cloudfront Origin Access (OAI) resource will fail since the current OAI resource is being used and cannot be removed.

## Versions
 - Terraform: v1.0.6
 - Provider(s): provider registry.terraform.io/hashicorp/aws v3.65.0
 - Module: terraform-aws-cloudfront v 2.9.0

## Reproduction
1. Create resources using the [complete example](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/tree/master/examples/complete) definitions
2. Update `module.cloudfront.origin_access_identities` key and `origin.s3_one.s3_origin_config.origin_access_identity` value to `s3_bucket_one_new_value`
3. Run `terraform plan` and confirm that terraform wants to recreate the OAI resource along with it's references on the cloudformation resource and bucket policy
4. Run `terraform apply` and check the execution fails with:
  ```
╷
│ Error: CloudFrontOriginAccessIdentityInUse: The CloudFront origin access identity is still being used.
│       status code: 409, request id: xxxxxxxx-853a-480d-xxxx-5fa5c26b9ab4
│
│
╵
```

## Expected behavior
Terraform apply should create the new OAI resource, update it where necessary and only then remove it.

## Actual behavior
Terraform apply tries to remove a resource being referenced and used and fails.

## Additional context
This can be fixed with a lifecycle block on the [OAI resource](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/main.tf#L5). This is not a common flow, but I needed to recreate the OAI resource since it was imported from an existing resource and wasn't working as expected.

```json
lifecycle {
    create_before_destroy = true
  }
```

Just wanted to check before sending a PR, please let me know.

Regards

**Comment by GMartinez-Sisti** [comment]
Not stale.

**Comment by antonbabenko** [comment]
Thanks @GMartinez-Sisti !

Sounds like a bug, please submit a PR for review.

**Comment by GMartinez-Sisti** [comment]
Thank you! PR created.
