### ISSUE TITLE
Use origin cache headers

### ISSUE THREAD

**Issue by xcaliber-tech** [terraform-aws-modules/terraform-aws-cloudfront#67]
Hello,
Is it possible to set up this cache behavior :
Legacy cache settings -> Object caching -> Use origin cache headers
I can't find the right option

![image](https://user-images.githubusercontent.com/73225624/152322052-c42b58cd-4ef5-4349-ace7-ef7c8b79190a.png)

-- 
guzik

**Comment by antonbabenko** [comment]
Yes, I think it is supported but it is not shown exactly in the `examples` folder.

The code is along these lines - https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/main.tf#L136-L149

**Comment by nokiomanz** [comment]
Hello,
Have you found what to use in the end xcaliber-tech?
I am looking to do the same thing.

**Comment by Lonli-Lokli** [comment]
@xcaliber-tech I think you can also do it this way (value taken from https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html)

```
default_cache_behavior = {
  cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
}
```
