### ISSUE TITLE
Output values

### ISSUE THREAD

**Issue by xcaliber-tech** [terraform-aws-modules/terraform-aws-cloudfront#68]
Hello,
Maybe it's not related to this module, but to my misunderstanding of Terraform. I want to use for_each calling this module, but I can't get outputs variables. Is there an example somewhere explaining how to do this?

```
│ Error: Unsupported attribute
│
│   on outputs.tf line 19, in output "cloudfront_distribution_domain_name":
│   19:   value = module.cdn[*].cloudfront_distribution_arn
│
│ This object does not have an attribute named "cloudfront_distribution_arn".
```

-- 
guzik

**Comment by antonbabenko** [comment]
I don't think it works this way. Please ask generic Terraform questions on https://discuss.hashicorp.com.
