### ISSUE TITLE
cache policy not working 

### ISSUE THREAD

**Issue by mohakar2022** [terraform-aws-modules/terraform-aws-cloudfront#71]
AWS Provider = version = "~>4.4"
CloudFront Version tag = v2.9.3

```
  default_cache_behavior = {
    target_origin_id           = "default"
    viewer_protocol_policy     = "https-only"


    allowed_methods = ["GET", "HEAD"]
    cached_methods  = ["GET", "HEAD"]
    compress        = true
    query_string    = true

    cache_policy_id            = "658327ea-f89d-4fab-a63d-7e88639e58f6"
    origin_request_policy_id   = "acba4595-bd28-49b8-b9fe-13317c0390fa"
    # This is id for SecurityHeadersPolicy copied from https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-response-headers-policies.html
    response_headers_policy_id = "67f7725c-6f97-4210-82d7-5512b31e9d03"
  }
```

`╷
│ Error: error creating CloudFront Distribution: InvalidArgument: The parameter ForwardedValues cannot be used when a cache policy is associated to the cache behavior.
│       status code: 400, request id: 959e4761-85b7-4105-bd68-eb574165fe7c
│ 
│   with module.cdn.aws_cloudfront_distribution.this[0],
│   on .terraform/modules/cdn/main.tf line 15, in resource "aws_cloudfront_distribution" "this":
│   15: resource "aws_cloudfront_distribution" "this" {`

**Comment by TBurda** [comment]
@mohakar2022 duplicate #40. Set `use_forwarded_values = false`
