### ISSUE TITLE
Please migrate this module to AWS v4 provider

### ISSUE THREAD

**Issue by alexgorb2016** [terraform-aws-modules/terraform-aws-cloudfront#74]
Hi,

Could it be possible to migrate this module this module to AWS provider v4?

With best regards,
Oleksandr.

**Comment by antonbabenko** [comment]
Hi @alexgorb2016 !

This module defines only the lowest version of Terraform (`>= 0.13.1`) and AWS provider (`>= 3.64`)- https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/versions.tf#L7

So, version 4 is working just fine.
