### ISSUE TITLE
Support for origin_access_control_id

### ISSUE THREAD

**Issue by rysi3k** [terraform-aws-modules/terraform-aws-cloudfront#78]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

Yes in 4.29.0

## Describe the solution you'd like.
I would like see support for https://github.com/hashicorp/terraform-provider-aws/pull/26508

**Comment by rysi3k** [comment]
PR: https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/79

**Comment by antonbabenko** [comment]
Fixed in #79
