### ISSUE TITLE
Error when cache_behavior is not supplied

### ISSUE THREAD

**Issue by mgaydarovaxway** [terraform-aws-modules/terraform-aws-cloudfront#8]
The field "cache_behavior" which is documented as optional is actually required. If omitted the following error occurs:

Error: Iteration over null value

  on .terraform/modules/<masked>/main.tf line 94, in resource "aws_cloudfront_distribution" "this":
  94:     for_each = [for k, v in var.cache_behavior : v if k == "default"]
    |----------------
    | var.cache_behavior is null

A null value cannot be used as the collection in a 'for' expression.

Error: Iteration over null value

  on .terraform/modules/<masked>/main.tf line 137, in resource "aws_cloudfront_distribution" "this":
 137:     for_each = [for k, v in var.cache_behavior : v if k != "default"]
    |----------------
    | var.cache_behavior is null

A null value cannot be used as the collection in a 'for' expression.

**Comment by joeky888** [comment]
This is on the roadmap, see https://github.com/hashicorp/terraform-provider-aws/issues/14373 .

**Comment by antonbabenko** [comment]
`default_cache_behavior` is required if `create_distribution` is set to `true`.

You can also update the module version to [v1.5.0](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/releases/v1.5.0) which has been just released where the ordering of cache behaviors has been fixed (ref #12).

Closing this issue.
