### ISSUE TITLE
Is it possible to add Cloudfront aliases to outputs?

### ISSUE THREAD

**Issue by strangeman** [terraform-aws-modules/terraform-aws-cloudfront#81]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: aws_cloudfront_distribution datasource have the `aliases` field

## Is your request related to a problem? Please describe.
My use case is adding CNAME records about Cloudfront distribution to DNS providers like Cloudflare. I can take the distribution domain name from the `cloudfront_distribution_domain_name` output, but cannot take aliases where that domain name should point to.

## Describe the solution you'd like.
I prefer output like `cloudfront_distribution_aliases` which contains all aliases to that distribution.

Something like that
```tf
resource "cloudflare_record" "cloudflare_record-test-example-com" {
  zone_id = data.cloudflare_zone.example-com.id
  name    = module.cloudfront.cloudfront_distribution_aliases[0]
  value   = module.cloudfront.cloudfront_distribution_domain_name
  type    = "CNAME"
  ttl     = 1
  proxied = true

  allow_overwrite = true
}
```

## Describe alternatives you've considered.
At this moment I solved that problem via tags (just added tag `domain` and got its value from `cloudfront_distribution_tags["domain"]`), but it is ugly workaround.

**Comment by antonbabenko** [comment]
There is no attribute for the `aliases` in the [`aws_cloudfront_distribution` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#attributes-reference).

You should use [aws_cloudfront_distribution data-source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_distribution#aliases) to get information about `aliases`.
