### ISSUE TITLE
Update creating create_origin_access_identity bases on the new approach of aws s3 

### ISSUE THREAD

**Issue by AndreyNovik1993** [terraform-aws-modules/terraform-aws-cloudfront#82]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
The old create_origin_access_identity mechanism is deprecated. 
Now it should be public bucket with access bases on the IAM Policies. 
Origin access control settings is recommended
Bucket can restrict access to only CloudFront.

## Describe the solution you'd like.
Could you update module for working with it ?

**Comment by antonbabenko** [comment]
I am unsure if I understand what is required to be updated in the module, so please open a PR with the proposed changes and updated examples.

**Comment by pawelpesz** [comment]
I think Andrey meant support for **Origin Access Control** which is now preferred over **Origin Access Identity**.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_origin_access_control

**Comment by antonbabenko** [comment]
@pawelpesz You're right. The PR should be rather straightforward if anyone wants to contribute.

**Comment by pawelpesz** [comment]
This is still an outstanding problem.
